version: 2
updates:
  # Dependabot updating root can break package updates since there are no tests for this in CI.
  # You should update root dependencies manually
  # - package-ecosystem: npm
  #   directory: "/"
  #   schedule:
  #     interval: weekly
  #   open-pull-requests-limit: 5
  #   target-branch: main

  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: main

  - package-ecosystem: npm
    directory: "/backend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: main

  - package-ecosystem: terraform
    directory: "/.infrastructure"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    target-branch: main
