#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run format:backend
npm run lint:backend

npm run format:frontend
npm run lint:frontend

terraform fmt -recursive

# Re-stage only files that were already staged, picking up formatter changes
git update-index --again
